/**
 * These tests execute the *real* compiled circuits (not a mock) through
 * @midnight-ntwrk/compact-runtime. Run `npm run compact` first so that
 * `managed/private-ballot/` exists -- see README "Testing" section.
 *
 * They cover:
 *  1. constructor initializes public ledger state correctly
 *  2. an eligible voter can cast a vote and the tally updates
 *  3. a voter cannot vote twice (nullifier reuse is rejected)
 *  4. a non-eligible secret is rejected
 *  5. the admin (and only the admin) can close voting; votes are then rejected
 *  6. the voter's raw secret key never appears anywhere in public ledger state
 */

import { describe, it, expect, beforeEach } from "vitest";
import {
  CircuitContext,
  QueryContext,
  constructorContext,
  emptyZswapLocalState,
  sampleContractAddress,
} from "@midnight-ntwrk/compact-runtime";
// Generated by `npm run compact` from src/private-ballot.compact
// eslint-disable-next-line import/no-unresolved
import { Contract, type Ledger, ledger } from "../managed/private-ballot/contract/index.js";
import {
  privateBallotWitnesses,
  createPrivateBallotSecretState,
  type PrivateBallotPrivateState,
} from "../witnesses/private-ballot-witnesses.js";
import { commitmentFor, generateVoterSecret, toHex } from "../witnesses/commitments.js";

const ADMIN_SECRET = generateVoterSecret();
const ADMIN_COMMITMENT = commitmentFor(ADMIN_SECRET);

const VOTERS = Array.from({ length: 3 }, () => {
  const secret = generateVoterSecret();
  return { secret, commitment: commitmentFor(secret) };
});

// Constructor takes a fixed 8-slot vector; pad unused slots with zeros.
function paddedVoterCommitments(): Uint8Array[] {
  const padded = VOTERS.map((v) => v.commitment);
  while (padded.length < 8) padded.push(new Uint8Array(32));
  return padded;
}

function freshContract() {
  const contract = new Contract<PrivateBallotPrivateState>(privateBallotWitnesses);
  const initialPrivateState = createPrivateBallotSecretState(new Uint8Array(32));

  const { currentPrivateState, currentContractState, currentZswapLocalState } =
    contract.initialState(
      constructorContext(initialPrivateState, "0".repeat(64)),
      ADMIN_COMMITMENT,
      "Should the treasury fund proposal #7?",
      paddedVoterCommitments()
    );

  const address = sampleContractAddress();
  let context = new CircuitContext(
    currentPrivateState,
    currentZswapLocalState,
    new QueryContext(currentContractState.data, address)
  );

  return { contract, address, context };
}

function withVoterSecret(context: CircuitContext<PrivateBallotPrivateState>, secret: Uint8Array) {
  return { ...context, currentPrivateState: createPrivateBallotSecretState(secret) };
}

describe("private-ballot contract", () => {
  let env: ReturnType<typeof freshContract>;

  beforeEach(() => {
    env = freshContract();
  });

  it("initializes public ledger state: open poll, zero tally, admin set", () => {
    const state: Ledger = ledger(env.context.transactionContext.state);
    expect(state.votingOpen).toBe(true);
    expect(toHex(state.admin)).toBe(toHex(ADMIN_COMMITMENT));
    expect(state.yesVotes).toBe(0n);
    expect(state.noVotes).toBe(0n);
  });

  it("lets an eligible voter cast a vote and updates the public tally", () => {
    const ctx = withVoterSecret(env.context, VOTERS[0].secret);
    const { context: next } = env.contract.impureCircuits.castVote(ctx, true);

    const state: Ledger = ledger(next.transactionContext.state);
    expect(state.yesVotes).toBe(1n);
    expect(state.noVotes).toBe(0n);
  });

  it("rejects a second vote from the same voter (nullifier reuse)", () => {
    const first = env.contract.impureCircuits.castVote(
      withVoterSecret(env.context, VOTERS[1].secret),
      false
    );

    expect(() =>
      env.contract.impureCircuits.castVote(
        withVoterSecret(first.context, VOTERS[1].secret),
        true
      )
    ).toThrow(/already cast/i);
  });

  it("rejects a vote from a secret that is not on the allowlist", () => {
    const outsider = generateVoterSecret();
    expect(() =>
      env.contract.impureCircuits.castVote(withVoterSecret(env.context, outsider), true)
    ).toThrow(/not an eligible voter/i);
  });

  it("lets the admin close voting, after which further votes are rejected", () => {
    const closed = env.contract.impureCircuits.closeVoting(
      withVoterSecret(env.context, ADMIN_SECRET)
    );
    const state: Ledger = ledger(closed.context.transactionContext.state);
    expect(state.votingOpen).toBe(false);

    expect(() =>
      env.contract.impureCircuits.castVote(
        withVoterSecret(closed.context, VOTERS[2].secret),
        true
      )
    ).toThrow(/voting is closed/i);
  });

  it("never writes a raw voter secret into public ledger state", () => {
    const { context: next } = env.contract.impureCircuits.castVote(
      withVoterSecret(env.context, VOTERS[0].secret),
      true
    );
    const serialized = toHex(next.transactionContext.state.serialize());
    for (const voter of VOTERS) {
      expect(serialized.includes(toHex(voter.secret))).toBe(false);
    }
    expect(serialized.includes(toHex(ADMIN_SECRET))).toBe(false);
  });
});
